#line 2 "slghscan.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 164
#define YY_END_OF_BUFFER 165
static yyconst short int yy_accept[531] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  165,   14,    7,    8,   14,   14,
        3,   13,    4,   13,   13,   13,   13,    5,    1,   58,
       56,   57,   58,   58,   58,   25,   51,   52,   52,   26,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   23,   22,   20,   21,   22,
       17,   19,   18,   15,   68,   66,   67,   61,   68,   61,
       64,   62,   64,   59,   96,   94,   95,   96,   96,   96,
       85,   88,   90,   91,   91,   88,   88,   90,   83,   84,
       87,   90,   90,   71,   86,   69,  161,  159,  160,  153,

      161,  161,  153,  153,  155,  156,  156,  153,  153,  153,
      153,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  153,   99,   97,  164,
      164,  163,  162,    7,    0,    6,    0,   13,   13,   13,
       13,   13,    1,    1,   56,    0,   55,    0,   50,    0,
       51,    0,    0,   52,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   23,   23,   20,    0,   19,   15,   15,
       66,    0,   65,    0,   64,   63,   59,   59,   94,   76,
        0,   89,    0,    0,    0,    0,   90,   90,    0,    0,

       91,   75,   77,   78,   74,   90,   90,   69,   69,  159,
      106,    0,  154,    0,  101,  155,    0,    0,  156,  104,
      107,  105,  108,  103,  102,  155,  155,  155,  155,  155,
      155,  155,  155,  155,    0,  118,  116,  117,  119,  122,
        0,  123,  155,  155,  144,  155,  155,  155,  155,  155,
      155,  155,  110,  109,  112,  113,  155,  155,  155,  155,
      155,  155,  100,   97,   97,    0,  163,  162,  162,    0,
       13,   13,   13,   13,    0,   54,   53,   51,   41,   51,
       51,   38,   51,   51,   37,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

        0,    0,    0,    0,   80,    0,   82,   93,   92,   90,
       90,    0,  158,  157,  133,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  121,  124,  120,  125,  155,  155,
      155,  155,  132,  155,  155,  155,  155,  114,  115,  111,
      155,  155,  155,  155,  155,  155,    2,    0,   13,   13,
       13,   12,   24,    0,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   43,   51,   51,
       28,   51,   51,   51,   16,    0,   60,    0,   70,    0,
       79,   81,   90,   90,   98,    0,  155,  155,  146,  155,
      135,  155,  155,  155,  155,  155,  155,  145,  155,  155,

      155,  155,  155,  155,  155,  155,  129,  134,  155,  126,
       13,   13,    9,   51,   51,   51,   51,   51,   51,   46,
       51,   51,   51,   51,   51,   51,   27,   32,   51,   51,
       51,   90,   90,  155,  151,  127,  141,  155,  155,  155,
      155,  136,  155,  152,  155,  155,  155,  137,  155,  155,
      140,   11,   10,   51,   51,   51,   51,   39,   42,   36,
       45,   51,   51,   51,   35,   47,   51,   51,   90,   72,
      128,  155,  155,  150,  155,  155,  155,  155,  147,  155,
      130,   51,   51,   33,   30,   49,   51,   51,   51,   51,
       90,  155,  155,  155,  155,  155,  155,  131,   51,   34,

       51,   51,   51,   44,   90,  155,  155,  155,  155,  155,
      143,   40,   29,   51,   48,   73,  155,  148,  155,  138,
      142,   51,  149,  155,   51,  139,   51,   51,   31,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   29,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       31,    1,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    1,    1,    1,    3,    1,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    1,    4,    3,
        1,    1,    1,    3,    4,    4,    4,    4,    4,    4,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[568] =
    {   0,
        0,  893,   64,  892,  128,  891,  192,  890,  256,  889,
      320,  888,    0,  382,  915,  922,  912,  922,  910,  902,
      922,    0,  922,  857,  871,  874,  865,  922,  904,  922,
      904,  922,  900,  901,  893,  922,    0,  350,  369,  922,
      856,  858,  851,  860,  850,  858,  853,  356,  855,  857,
      357,  350,  345,  858,  843,  888,  922,  888,  922,  879,
      922,    0,  922,  885,  922,  885,  922,  922,  881,  875,
        0,  922,  831,  880,  922,  880,  922,  856,  877,  385,
      922,  922,  863,  361,  393,  374,  376,    0,  922,  922,
      922,  832,  829,  922,  922,  873,  922,  873,  922,  849,

      870,  862,  922,  862,    0,  367,  397,  382,  845,  396,
      836,  832,  374,  389,  828,  808,  423,  816,  397,  815,
      391,  814,  393,  436,  810,  822,  798,  922,  856,  922,
      855,  922,  854,  854,  852,  922,    0,    0,  800,  813,
      815,  797,  847,  922,  847,  843,  842,  843,  922,    0,
        0,  432,    0,  436,  802,  392,  796,  421,  805,  784,
      787,  793,  799,  798,  788,  789,  794,  411,  799,  788,
      782,  413,  779,  827,  922,  827,    0,    0,  825,  922,
      825,  821,  820,    0,    0,    0,  821,  922,  821,  922,
      819,  922,    0,  773,  768,  770,  802,    0,  445,    0,

      458,  922,  922,  922,  922,  768,  773,  812,  922,  812,
      922,  810,  922,    0,  922,    0,  448,    0,  462,  922,
      922,  922,  922,  922,  922,  759,  759,  767,  422,  766,
      759,  758,  760,  755,  779,  922,  922,  922,  922,  778,
      777,  776,  751,  745,    0,  744,  760,  748,  738,  744,
      739,  737,  922,  922,  766,  459,  741,  754,  730,  735,
      731,  727,  922,  781,  922,  780,  922,  779,  922,  770,
      745,  736,  726,  735,  765,  470,    0,  734,    0,  722,
      719,    0,  737,  728,    0,  716,  730,  722,  714,  728,
      731,  721,  715,  723,  724,  721,  720,  703,  714,  718,

      744,  743,  742,  714,  922,  699,    0,  472,    0,  714,
      702,  737,  474,    0,    0,  695,  700,  699,  692,  697,
      693,  688,  705,  690,  922,  922,  922,  922,  451,  689,
      717,  701,    0,  686,  697,  678,  684,  922,  922,  922,
      679,  678,  675,  674,  679,  672,  922,  714,  687,  675,
      673,    0,  922,  710,  672,  684,  679,  662,  681,  669,
      661,  664,  673,  672,  657,  656,  669,    0,  668,  658,
        0,  666,  669,  650,  922,  691,  922,  690,  922,  689,
      922,  922,  664,  648,  922,  686,  647,  657,    0,  635,
        0,  647,  639,  632,  638,  635,  636,    0,  647,  640,

      649,  635,  631,  644,  629,  628,    0,    0,  642,    0,
      636,  638,    0,  629,  627,  616,  627,  624,  632,    0,
      613,  615,  619,  617,  612,  627,    0,    0,  611,  627,
      619,  615,  614,  602,    0,    0,    0,  622,  604,  602,
      635,    0,  608,    0,  609,  597,  603,    0,  601,  590,
        0,    0,    0,  609,  606,  592,  591,    0,    0,    0,
        0,  594,  608,  603,    0,    0,  595,  580,  586,    0,
        0,  583,  591,    0,  596,  586,  595,  585,    0,  575,
        0,  583,  591,    0,    0,    0,  592,  576,  588,  587,
      586,  581,  574,  576,  586,  583,  565,    0,  564,    0,

      578,  582,  562,    0,  560,  567,  558,  562,  556,  555,
        0,    0,    0,  555,    0,    0,  569,    0,  464,    0,
        0,  448,    0,  443,  461,    0,  458,  455,    0,  922,
      500,  504,  508,  510,  514,  518,  522,  524,  528,  530,
      534,  538,  540,  544,  548,  550,  554,  558,  560,  564,
      568,  572,  574,  576,  466,  578,  580,  582,  427,  584,
      405,  587,  590,  593,  596,  599,  602
    } ;

static yyconst short int yy_def[568] =
    {   0,
      530,    1,  530,    3,  530,    5,  530,    7,  530,    9,
      530,   11,  531,  532,  530,  530,  530,  530,  533,  530,
      530,  534,  530,  534,  534,  534,  534,  530,  535,  530,
      530,  530,  536,  537,  530,  530,  538,  530,  530,  530,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  539,  530,  530,  530,  530,
      530,  540,  530,  541,  530,  530,  530,  530,  542,  530,
      543,  530,  543,  544,  530,  530,  530,  530,  545,  530,
      530,  530,  546,  530,  530,  530,  530,  546,  530,  530,
      530,  546,  546,  530,  530,  547,  530,  530,  530,  530,

      548,  530,  530,  530,  549,  530,  530,  530,  530,  530,
      530,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  530,  530,  550,  530,
      551,  530,  552,  530,  533,  530,  553,  534,  534,  534,
      534,  534,  535,  530,  530,  536,  530,  537,  530,  554,
      538,  530,  555,  530,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  539,  530,  530,  556,  540,  541,  530,
      530,  542,  530,  557,  543,  543,  544,  530,  530,  530,
      545,  530,  558,  530,  530,  530,  546,  546,  530,  559,

      530,  530,  530,  530,  530,  546,  546,  547,  530,  530,
      530,  548,  530,  560,  530,  549,  530,  561,  530,  530,
      530,  530,  530,  530,  530,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  530,  530,  530,  530,  530,  530,
      530,  530,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  530,  530,  530,  530,  549,  549,  549,  549,
      549,  549,  530,  550,  530,  551,  530,  552,  530,  562,
      534,  534,  534,  534,  563,  530,  555,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      564,  565,  566,  530,  530,  530,  546,  530,  559,  546,
      546,  567,  530,  561,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  530,  530,  530,  530,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  530,  530,  530,
      549,  549,  549,  549,  549,  549,  530,  562,  534,  534,
      534,  534,  530,  563,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  530,  564,  530,  565,  530,  566,
      530,  530,  546,  546,  530,  567,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      534,  534,  534,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  546,  546,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  534,  534,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  546,  546,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      546,  549,  549,  549,  549,  549,  549,  549,  538,  538,

      538,  538,  538,  538,  546,  549,  549,  549,  549,  549,
      549,  538,  538,  538,  538,  546,  549,  549,  549,  549,
      549,  538,  549,  549,  538,  549,  538,  538,  538,    0,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530
    } ;

static yyconst short int yy_nxt[987] =
    {   0,
       16,   17,   18,   16,   16,   19,   20,   16,   16,   21,
       21,   16,   16,   21,   21,   22,   16,   16,   16,   16,
       16,   23,   16,   16,   16,   16,   16,   16,   22,   22,
       16,   16,   16,   22,   24,   22,   22,   25,   22,   22,
       22,   22,   22,   22,   22,   22,   26,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   27,   22,   22,   22,
       28,   16,   16,   16,   30,   31,   32,   30,   33,   34,
       35,   30,   30,   36,   36,   30,   30,   36,   30,   37,
       30,   38,   39,   39,   39,   36,   40,   30,   36,   30,
       30,   30,   37,   37,   36,   36,   30,   37,   41,   42,

       43,   44,   45,   37,   37,   46,   37,   37,   37,   47,
       37,   48,   49,   50,   37,   51,   52,   53,   37,   54,
       55,   37,   37,   37,   30,   30,   30,   30,   57,   58,
       59,   57,   57,   57,   60,   57,   57,   61,   61,   57,
       57,   61,   57,   62,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   62,   62,   57,   57,
       57,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   63,   57,
       57,   57,   65,   66,   67,   68,   69,   68,   70,   68,

       68,   68,   68,   68,   68,   68,   68,   71,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       71,   71,   68,   68,   72,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   73,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   68,   68,   68,   68,   75,   76,   77,   78,
       75,   79,   80,   75,   81,   82,   82,   82,   82,   82,
       82,   83,   82,   84,   85,   85,   85,   82,   82,   86,
       82,   87,   75,   75,   88,   88,   89,   90,   91,   88,
       88,   88,   88,   88,   88,   88,   92,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       93,   88,   88,   88,   88,   88,   94,   95,   75,   82,
       97,   98,   99,  100,   97,  101,  102,  103,  104,  103,
      103,  103,  103,  103,  103,  105,  103,  106,  107,  107,
      107,  103,  103,  108,  109,  110,   97,   97,  105,  105,
      103,  103,  111,  105,  112,  113,  114,  115,  116,  117,
      118,  105,  119,  105,  105,  120,  105,  121,  105,  122,
      105,  123,  124,  125,  105,  105,  105,  105,  105,  126,
       97,  127,  128,  103,  132,  152,  154,  154,  154,  154,
      162,  166,  168,  170,  193,  167,  199,  202,  203,  169,

      204,  205,  217,  171,  163,  220,  221,  153,  314,  133,
      201,  201,  201,  201,  219,  219,  219,  219,  200,  194,
      223,  224,  227,  229,  218,  248,  235,  230,  228,  249,
      309,  251,  279,  195,  236,  237,  245,  238,  231,  239,
      232,  252,  196,  253,  246,  280,  240,  241,  242,  276,
      276,  293,  254,  154,  154,  154,  154,  282,  298,  255,
      283,  256,  308,  308,  299,  313,  313,  318,  243,  277,
      294,  257,  258,  319,  259,  201,  201,  201,  201,  219,
      219,  219,  219,  339,  340,  396,  260,  276,  276,  308,
      308,  313,  313,  529,  528,  527,  526,  525,  524,  397,

      130,  130,  130,  130,  131,  131,  131,  131,  135,  135,
      135,  135,  138,  138,  143,  143,  143,  143,  146,  146,
      146,  146,  148,  148,  148,  148,  151,  151,  174,  174,
      174,  174,  178,  178,  179,  179,  179,  179,  182,  182,
      182,  182,  185,  185,  187,  187,  187,  187,  191,  191,
      191,  191,  198,  198,  208,  208,  208,  208,  212,  212,
      212,  212,  216,  216,  264,  264,  264,  264,  266,  266,
      266,  266,  268,  268,  268,  268,  270,  270,  275,  275,
      301,  301,  302,  302,  303,  303,  312,  312,  348,  348,
      348,  354,  354,  354,  376,  376,  376,  378,  378,  378,

      380,  380,  380,  386,  386,  386,  523,  522,  521,  520,
      519,  518,  517,  516,  515,  514,  513,  512,  511,  510,
      509,  508,  507,  506,  505,  504,  503,  502,  501,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  475,  474,  473,  472,  471,  470,
      469,  468,  467,  466,  465,  464,  463,  462,  461,  460,
      459,  458,  457,  456,  455,  454,  453,  452,  451,  450,
      449,  448,  447,  446,  445,  444,  443,  442,  441,  440,
      439,  438,  437,  436,  435,  434,  385,  433,  432,  379,

      377,  375,  431,  430,  429,  428,  427,  426,  425,  424,
      423,  422,  421,  420,  419,  418,  417,  416,  415,  414,
      353,  413,  412,  411,  347,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  385,  384,  383,
      382,  381,  379,  377,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  353,  352,  351,  350,  349,
      347,  269,  267,  265,  346,  345,  344,  343,  342,  341,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,

      328,  327,  326,  325,  324,  323,  322,  321,  320,  317,
      316,  315,  213,  210,  209,  311,  310,  307,  306,  305,
      304,  192,  189,  188,  182,  183,  181,  180,  176,  175,
      300,  297,  296,  295,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  281,  278,  149,  146,  147,  145,  144,
      274,  273,  272,  271,  136,  134,  269,  267,  265,  263,
      262,  261,  250,  247,  244,  234,  233,  226,  225,  222,
      215,  214,  213,  211,  210,  209,  207,  206,  197,  192,
      190,  189,  188,  186,  184,  183,  181,  180,  177,  176,
      175,  173,  172,  165,  164,  161,  160,  159,  158,  157,

      156,  155,  150,  149,  147,  145,  144,  142,  141,  140,
      139,  137,  136,  134,  530,  129,   96,   74,   64,   56,
       29,   15,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530
    } ;

static yyconst short int yy_chk[987] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   14,   38,   39,   39,   39,   39,
       48,   51,   52,   53,   80,   51,   84,   86,   86,   52,

       87,   87,  106,   53,   48,  108,  108,   38,  561,   14,
       85,   85,   85,   85,  107,  107,  107,  107,   84,   80,
      110,  110,  113,  114,  106,  121,  117,  114,  113,  121,
      559,  123,  156,   80,  117,  117,  119,  117,  114,  117,
      114,  123,   80,  124,  119,  156,  117,  117,  117,  152,
      152,  168,  124,  154,  154,  154,  154,  158,  172,  124,
      158,  124,  199,  199,  172,  217,  217,  229,  117,  555,
      168,  124,  124,  229,  124,  201,  201,  201,  201,  219,
      219,  219,  219,  256,  256,  329,  124,  276,  276,  308,
      308,  313,  313,  528,  527,  525,  524,  522,  519,  329,

      531,  531,  531,  531,  532,  532,  532,  532,  533,  533,
      533,  533,  534,  534,  535,  535,  535,  535,  536,  536,
      536,  536,  537,  537,  537,  537,  538,  538,  539,  539,
      539,  539,  540,  540,  541,  541,  541,  541,  542,  542,
      542,  542,  543,  543,  544,  544,  544,  544,  545,  545,
      545,  545,  546,  546,  547,  547,  547,  547,  548,  548,
      548,  548,  549,  549,  550,  550,  550,  550,  551,  551,
      551,  551,  552,  552,  552,  552,  553,  553,  554,  554,
      556,  556,  557,  557,  558,  558,  560,  560,  562,  562,
      562,  563,  563,  563,  564,  564,  564,  565,  565,  565,

      566,  566,  566,  567,  567,  567,  517,  514,  510,  509,
      508,  507,  506,  505,  503,  502,  501,  499,  497,  496,
      495,  494,  493,  492,  491,  490,  489,  488,  487,  483,
      482,  480,  478,  477,  476,  475,  473,  472,  469,  468,
      467,  464,  463,  462,  457,  456,  455,  454,  450,  449,
      447,  446,  445,  443,  441,  440,  439,  438,  434,  433,
      432,  431,  430,  429,  426,  425,  424,  423,  422,  421,
      419,  418,  417,  416,  415,  414,  412,  411,  409,  406,
      405,  404,  403,  402,  401,  400,  399,  397,  396,  395,
      394,  393,  392,  390,  388,  387,  386,  384,  383,  380,

      378,  376,  374,  373,  372,  370,  369,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  351,  350,  349,  348,  346,  345,  344,  343,  342,
      341,  337,  336,  335,  334,  332,  331,  330,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  312,  311,  310,
      306,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      284,  283,  281,  280,  278,  275,  274,  273,  272,  271,
      270,  268,  266,  264,  262,  261,  260,  259,  258,  257,
      255,  252,  251,  250,  249,  248,  247,  246,  244,  243,

      242,  241,  240,  235,  234,  233,  232,  231,  230,  228,
      227,  226,  212,  210,  208,  207,  206,  197,  196,  195,
      194,  191,  189,  187,  183,  182,  181,  179,  176,  174,
      173,  171,  170,  169,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  157,  155,  148,  147,  146,  145,  143,
      142,  141,  140,  139,  135,  134,  133,  131,  129,  127,
      126,  125,  122,  120,  118,  116,  115,  112,  111,  109,
      104,  102,  101,  100,   98,   96,   93,   92,   83,   79,
       78,   76,   74,   73,   70,   69,   66,   64,   60,   58,
       56,   55,   54,   50,   49,   47,   46,   45,   44,   43,

       42,   41,   35,   34,   33,   31,   29,   27,   26,   25,
       24,   20,   19,   17,   15,   12,   10,    8,    6,    4,
        2,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530,  530,  530,  530,  530,
      530,  530,  530,  530,  530,  530
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "slghscan.l"
#define INITIAL 0
/* ###
 * IP: GHIDRA
 * NOTE: flex skeletons are NOT bound by flex's BSD license
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#define YY_NEVER_INTERACTIVE 1
#line 19 "slghscan.l"
#include "slgh_compile.h"
#include "slghparse.tab.h"
#define yywrap() 1
#define YY_SKIP_YYWRAP

struct FileStreamState {
  YY_BUFFER_STATE lastbuffer;	// Last lex buffer corresponding to the stream
  FILE *file;                   // The NEW file stream
};

extern SleighCompile *slgh;
int4 last_preproc;   // lex state before last preprocessing erasure
int4 actionon;       // whether '&' '|' and '^' are treated as actionon in pattern section
int4 withsection = 0; // whether we are between the 'with' keyword and its open brace '{'
struct dynarray filebuffers;
struct dynarray ifstack;
int4 negative_if = -1;

#define fss_back()       ((struct FileStreamState *)dynarray_back(&filebuffers))
#define skip_space(s)       while (isspace(*s)) s++;
#define ifstack_push(a)     dynarray_add(&ifstack, (void *)a)
#define ifstack_back()        ((int)dynarray_back(&ifstack))
#define ifstack_back_set(i)      (dynarray_back(&ifstack)) = (void *)i
#define ifstack_pop()      ifstack.len --

#define fss_new()         calloc(1, sizeof (struct FileStreamState))

void check_to_endofline(const char *s)

{ // Make sure there is nothing to the end of the line
  skip_space(s);
  if (s[0])
    if (s[0] != '#')
      vm_error("Extra characters in preprocessor directive"); 
}

CString *read_identifier(char **old, CString *res)

{  // Read a proper identifier from the stream
  char *s = *old;
  skip_space(s);

  char *from = s;
  while (*s && (isalnum(*s) || *s == '_')) s++;

  cstr_cat(res, from, s - from);

  *old = s;
  return res;
}

void preprocess_string(char **old, CString *res)

{  // Grab string surrounded by double quotes from stream or call preprocess_error
  char *s = *old;
  char *t;
  
  skip_space(s);
  if (s[0] != '\"')
    vm_error("Expecting double quoted string, %s", s);
  s++;
  t = strchr(s, '\"');
  if (!t)
      vm_error("Missing terminating double quote");

  cstr_cat(res, s, t - s);

  *old = ++t;
}

extern int4 preprocess_if(char **old);

int4 read_defined_operator(char **old)

{  // We have seen a -defined- keyword in an if or elif
   // Read macro name used as input, return 1 if it is defined
   char *s = *old;
  char tok = ' ';
  CSTR_INIT(macroname);
  
  skip_space(s);
  if (s[0] != '(')
    vm_error("Badly formed \"defined\" operator");
  ++s;
  read_identifier(&s, &macroname);
  int4 res = slgh_get_macro(slgh, macroname.data, NULL) ? 1 : 0;
  skip_space(s);
  if (s[0] != ')')
    vm_error("Badly formed \"defined\" operator");
  *old = ++s;
  return res;
}

int4 read_boolean_clause(char **old)

{				// We have seen an if or elif
				// return 1 if condition is true or else 0
  int ret = 0;
  char *s = *old;
  skip_space(s);
  if (*s =='(') {		// Parenthetical expression spawns recursion
    int4 val = *++s;
    int4 res = preprocess_if(&s);
    skip_space(s);
    val = *++s;
    if (val != ')')
      vm_error("Unbalanced parentheses");

    *old = s;
    return res;
  }
				// Otherwise we must have a normal comparison operator
  CSTR_INIT(lhs);
  CSTR_INIT(rhs);
  char *comp, *lhs_val = "\0", *rhs_val = "\0";

  if (s[0] =='\"')		// Read left-hand side string
    preprocess_string(&s,&lhs);
  else {
    read_identifier(&s, &lhs);
    if (!strcmp(lhs.data, "defined")) {
      ret = read_defined_operator(&s);
      goto exit_label;
    }
    if (!slgh_get_macro(slgh, lhs.data, &lhs_val))
      vm_error("Could not find preprocessor macro %s", lhs.data);
  }

  skip_space(s);

  comp = s;
  s += 2;

  skip_space(s);
  if (*s =='\"') {// Read right-hand side string
    preprocess_string(&s,&rhs);
  }
  else {
    read_identifier(&s, &rhs);
    if (!slgh_get_macro(slgh, rhs.data, &rhs_val))
      vm_error("Could not find preprocessor macro %s", rhs.data);
  }

  if (!strncmp(comp, "==", 2)) {
    ret = !strcmp (lhs_val, rhs_val) ? 1 : 0;
  }
  else if (!strncmp(comp, "!=", 2))
    ret = strcmp(lhs_val, rhs_val) ? 1 : 0;
  else
    vm_error("Syntax error in condition");

exit_label:
  cstr_free(&lhs);
  cstr_free(&rhs);

  *old = s;
  return ret;
}

int4 preprocess_if(char **old)

{
  char *s = *old;
  int4 res = read_boolean_clause(&s);
  skip_space(s);
  while(s[0] && (s[0] != ')')) {
    char *boolop = s;

    s += 2;
    int4 res2 = read_boolean_clause(&s);
    if (!strncmp(boolop, "&&", 2))
      res = res & res2;
    else if (!strncmp(boolop, "||", 2))
      res = res | res2;
    else if (!strncmp(boolop, "^^", 2))
      res = res ^ res2;
    else
      vm_error("Syntax error in expression");

    skip_space(s);
  }

  *old = s;
  return res;
}

void expand_preprocmacros(CString *cstr)

{
  CSTR_INIT(macro);
  CSTR_INIT(res);
  char *lastpos = NULL, *value;
  char *pos = strstr(cstr->data, "$(");
  char *end = (char *)cstr->data + cstr->size;
  if (!pos) return;

  for(;;) {
    if (NULL == pos) {
      cstr_cat(&res, lastpos, end - lastpos);
      cstr_free(cstr);
      cstr_cat(cstr, res.data, res.size);

      cstr_free(&res);
      return;
    }

    cstr_cat(&res, lastpos, (pos - lastpos));
    lastpos = strchr(pos, ')');
    if (!lastpos) {
      vm_error("Unterminated macro in string, %s", cstr->data);
    }

    macro.data = pos + 2;
    macro.size = lastpos - (char *)macro.data;
    if (!slgh_get_macro(slgh, macro.data, &value)) {
      vm_error("Unknown preprocessing macro %s", macro.data);
    }
    cstr_cat(&res, value, strlen(value));

    pos = strstr(++lastpos, "$(");
  }
}


int4 preprocess(int4 cur_state,int4 blank_state)

{
  CSTR_INIT(varname);
  CSTR_INIT(value);
  char *str = str_new(yytext, 0);
  char *comment = strchr (str, '#');
  char *filename;
  if (comment) {
    *comment = 0;
  }
  char *s = str;
  CSTR_INIT(type);

  if (cur_state != blank_state)
    last_preproc = cur_state;

// skip @
  s++; 
  read_identifier(&s, &type);
  if (!strcmp(type.data, "include")) {
    if (negative_if == -1) {  // Not in the middle of a false if clause
      dynarray_add(&filebuffers, fss_new());
      fss_back()->lastbuffer = YY_CURRENT_BUFFER;
      fss_back()->file = 0;
      skip_space(s);
      CSTR_INIT(fname);
      preprocess_string(&s,&fname);
      expand_preprocmacros(&fname);
      SleighCompile_parseFromNewFile(slgh, fname.data);
      cstr_free(&fname);
      filename = SleighCompile_grabCurrentFilePath(slgh);
      yyin = fopen(filename,"r");
      if (yyin == (FILE *)0) {
        vm_error("Could not open included file %s", filename);
      }
      fss_back()->file = yyin;
      yy_switch_to_buffer( yy_create_buffer(yyin, YY_BUF_SIZE) );
      check_to_endofline(s);
    }
  }
  else if (!strcmp(type.data, "define")) {
    if (negative_if == -1) {
      read_identifier(&s, &varname);   // Get name of variable being defined
      skip_space(s);
      if (s[0] == '\"')
        preprocess_string(&s,&value);
      else
        read_identifier(&s, &value);
      if (varname.size ==0)
        vm_error("Error in preprocessor definition");
      slgh_set_macro(slgh, varname.data, value.data);
      check_to_endofline(s);
    }
  }
  else if (!strcmp (type.data, "undef")) {
    if (negative_if == -1) {
      read_identifier(&s, &varname);		// Name of variable to undefine
      if (varname.size ==0)
        vm_error("Error in preprocessor undef");
      slgh_del_macro(slgh, varname.data);
      check_to_endofline(s);
    }
  }
  else if (!strcmp(type.data, "ifdef")) {
    read_identifier(&s, &varname);
    if (varname.size ==0)
      vm_error("Error in preprocessor ifdef");
    int4 truth = (slgh_get_macro(slgh, varname.data, NULL)) ? 1 : 0;

    ifstack_push(truth);
    check_to_endofline(s);
  }
  else if (!strcmp(type.data, "ifndef")) {
    read_identifier(&s, &varname);
    if (varname.size ==0)
      vm_error("Error in preprocessor ifndef");
    int4 truth = (slgh_get_macro(slgh, varname.data, NULL)) ? 0 : 1;	// flipped from ifdef

    ifstack_push(truth);
    check_to_endofline(s);
  }
  else if (!strcmp(type.data, "if")) {
    int4 truth = preprocess_if(&s);
    if (s[0])
      vm_error("Unbalanced parentheses");
    ifstack_push(truth);
  }
  else if (!strcmp(type.data, "elif")) {
    if (ifstack.len == 0)
      vm_error("elif without preceding if");
    if ((ifstack_back()&2)!=0)		// We have already seen an else clause
      vm_error("elif follows else");
    if ((ifstack_back()&4)!=0)          // We have already seen a true elif clause
      ifstack_back_set(4);               // don't include any other elif clause
    else if ((ifstack_back()&1)!=0)     // Last clause was a true if
      ifstack_back_set(4);               // don't include this elif
    else {
      int4 truth = preprocess_if(&s);
      if (!s[0])
        vm_error("Unbalanced parentheses");
      if (truth==0)
        ifstack_back_set(0);
      else
        ifstack_back_set(5);
    }
  }
  else if (!strcmp(type.data, "endif")) {
    if (!ifstack.len)
      vm_error("preprocessing endif without matching if");
    ifstack_pop();
    check_to_endofline(s);
  }
  else if (!strcmp(type.data, "else")) {
    if (!ifstack.len)
      vm_error("preprocessing else without matching if");
    if ((ifstack_back()&2)!=0)
      vm_error("second else for one if");
    if ((ifstack_back()&4)!=0)       // Seen a true elif clause before
      ifstack_back_set(6);
    else if (ifstack_back()==0)
      ifstack_back_set(3);
    else
      ifstack_back_set(2);
    check_to_endofline(s);
  }
  else
    vm_error("Unknown preprocessing directive: %s", type);

  if (negative_if >= 0) {  // We were in a false state
    if (negative_if+1 < ifstack.len)
      return blank_state;  // false state is still deep in stack
    else                   // false state is popped off or is current and changed
      negative_if = -1;
  }
  if (!ifstack.len) return last_preproc;
  if ((ifstack_back()&1)==0) {
    negative_if = ifstack.len -1;
    return blank_state;
  }

  cstr_free(&varname);
  cstr_free(&value);
  cstr_free(&type);
  str_free(str);

  return last_preproc;
}

void preproc_macroexpand(void)

{
  dynarray_add(&filebuffers, vm_mallocz(sizeof (struct FileStreamState)));
  fss_back()->lastbuffer = YY_CURRENT_BUFFER;
  fss_back()->file = (FILE *)0;
  CSTR_INIT(macro);
  char *value = NULL;

  cstr_cat(&macro, yytext + 2, strlen(yytext) - 3);

  if (!slgh_get_macro(slgh, macro.data, &value))
    vm_error("Unknown preprocessing macro %s", macro.data);
  yy_switch_to_buffer( yy_scan_string( value ) );
  SleighCompile_parsePreprocMacro(slgh);
  cstr_free(&macro);
}

int4 find_symbol(void) {
  CString *newstring = cstr_new(yytext, strlen(yytext));
  SleighSymbol *sym = SleighCompile_findSymbol(slgh, newstring->data);
  if (sym == (SleighSymbol *)0) {
    yylval.str = newstring;
    return STRING;
  }
  cstr_delete (newstring);
  switch(sym->type) {
  case section_symbol:
    yylval.sectionsym = (SectionSymbol *)sym;
    return SECTIONSYM;
  case space_symbol:
    yylval.spacesym = (SpaceSymbol *)sym;
    return SPACESYM;
  case token_symbol:
    yylval.tokensym = (TokenSymbol *)sym;
    return TOKENSYM;
  case userop_symbol:
    yylval.useropsym = (UserOpSymbol *)sym;
    return USEROPSYM;
  case value_symbol:
    yylval.valuesym = (ValueSymbol *)sym;
    return VALUESYM;
  case valuemap_symbol:
    yylval.valuemapsym = (ValueMapSymbol *)sym;
    return VALUEMAPSYM;
  case name_symbol:
    yylval.namesym = (NameSymbol *)sym;
    return NAMESYM;
  case varnode_symbol:
    yylval.varsym = (VarnodeSymbol *)sym;
    return VARSYM;
  case bitrange_symbol:
    yylval.bitsym = (BitrangeSymbol *)sym;
    return BITSYM;
  case varnodelist_symbol:
    yylval.varlistsym = (VarnodeListSymbol *)sym;
    return VARLISTSYM;
  case operand_symbol:
    yylval.operandsym = (OperandSymbol *)sym;
    return OPERANDSYM;
  case start_symbol:
    yylval.startsym = (StartSymbol *)sym;
    return STARTSYM;
  case end_symbol:
    yylval.endsym = (EndSymbol *)sym;
    return ENDSYM;
  case subtable_symbol:
    yylval.subtablesym = (SubtableSymbol *)sym;
    return SUBTABLESYM;
  case macro_symbol:
    yylval.macrosym = (MacroSymbol *)sym;
    return MACROSYM;
  case label_symbol:
    yylval.labelsym = (LabelSymbol *)sym;
    return LABELSYM;
  case epsilon_symbol:
    yylval.specsym = (SpecificSymbol *)sym;
    return SPECSYM;
  case context_symbol:
    yylval.contextsym = (ContextSymbol *)sym;
    return CONTEXTSYM;
  case dummy_symbol:
    break;
  }
  //return -1;   // Should never reach here
  vm_error("should never reach here, sym->name = %s, sym->type = %d", sym->name, sym->type);
  return -1;
}

int4 scan_number(char *numtext,YYSTYPE *lval,bool signednum)

{
  uintb val;
  if (numtext[0] == '0' && numtext[1] == 'b') {
    val = 0;
    numtext += 2;
    while ((*numtext) != 0) {
      val <<= 1;
      if (*numtext == '1') {
        val |= 1;
      }
      ++numtext;
    }
  } 
  else if (numtext[0] == '0' && (numtext[1] == 'x' || numtext[1] == 'X')) {
    val = strtoull(numtext, NULL, 16);
  }
  else if (numtext[0] == '0'){
    val = strtoull(numtext, NULL, 8);
  }
  else if (numtext[0] >= '1' && numtext[0] <= '9') {
    val = strtoull(numtext, NULL, 10);
  }
  else {
      vm_error("bad integer %s", numtext);
  }
  if (signednum) {
    lval->big = val;
    return INTB;
  }
  lval->i = val;
  return INTEGER;
}

#define defblock 1

#define macroblock 2

#define print 3

#define pattern 4

#define sem 5

#define preproc 6

#line 1290 "slghscan.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 524 "slghscan.l"


#line 1447 "slghscan.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 531 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 922 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 526 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(INITIAL,preproc) ); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 527 "slghscan.l"
{ preproc_macroexpand(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 528 "slghscan.l"
{ yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 529 "slghscan.l"
{ BEGIN(print); SleighCompile_calcContextLayout(slgh); yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 530 "slghscan.l"
{ BEGIN(sem); yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 531 "slghscan.l"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 532 "slghscan.l"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 533 "slghscan.l"
{ SleighCompile_nextLine(slgh); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 534 "slghscan.l"
{ BEGIN(macroblock); return MACRO_KEY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 535 "slghscan.l"
{ BEGIN(defblock); return DEFINE_KEY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 536 "slghscan.l"
{ BEGIN(defblock); SleighCompile_calcContextLayout(slgh); return ATTACH_KEY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 537 "slghscan.l"
{ BEGIN(pattern); withsection = 1; SleighCompile_calcContextLayout(slgh); return WITH_KEY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 538 "slghscan.l"
{  return find_symbol();  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 539 "slghscan.l"
{ return yytext[0]; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 541 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(macroblock,preproc) ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 542 "slghscan.l"
{ preproc_macroexpand(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 543 "slghscan.l"
{ yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 544 "slghscan.l"
{ BEGIN(sem); return yytext[0]; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 545 "slghscan.l"
{  yylval.str = cstr_new(yytext, strlen(yytext)); return STRING;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 546 "slghscan.l"

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 547 "slghscan.l"
{ SleighCompile_nextLine(slgh); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 548 "slghscan.l"
{ return yytext[0]; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 550 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(defblock,preproc) ); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 551 "slghscan.l"
{ preproc_macroexpand(); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 552 "slghscan.l"
{ yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 553 "slghscan.l"
{ BEGIN(INITIAL); yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 554 "slghscan.l"
{ return SPACE_KEY; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 555 "slghscan.l"
{ return TYPE_KEY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 556 "slghscan.l"
{ return RAM_KEY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 557 "slghscan.l"
{ return DEFAULT_KEY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 558 "slghscan.l"
{ return REGISTER_KEY; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 559 "slghscan.l"
{ return TOKEN_KEY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 560 "slghscan.l"
{ return CONTEXT_KEY; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 561 "slghscan.l"
{ return BITRANGE_KEY; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 562 "slghscan.l"
{ return SIGNED_KEY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 563 "slghscan.l"
{ return NOFLOW_KEY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 564 "slghscan.l"
{ return HEX_KEY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 565 "slghscan.l"
{ return DEC_KEY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 566 "slghscan.l"
{ return ENDIAN_KEY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 567 "slghscan.l"
{ return ALIGN_KEY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 568 "slghscan.l"
{ return BIG_KEY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 569 "slghscan.l"
{ return LITTLE_KEY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 570 "slghscan.l"
{ return SIZE_KEY; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 571 "slghscan.l"
{ return WORDSIZE_KEY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 572 "slghscan.l"
{ return OFFSET_KEY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 573 "slghscan.l"
{ return NAMES_KEY; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 574 "slghscan.l"
{ return VALUES_KEY; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 575 "slghscan.l"
{ return VARIABLES_KEY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 576 "slghscan.l"
{ return PCODEOP_KEY; }
	YY_BREAK
case 50:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 577 "slghscan.l"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 578 "slghscan.l"
{  return find_symbol();  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 579 "slghscan.l"
{ return scan_number(yytext,&yylval,false); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 580 "slghscan.l"
{ return scan_number(yytext,&yylval,false); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 581 "slghscan.l"
{ return scan_number(yytext,&yylval,false); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 582 "slghscan.l"
{ yylval.str = cstr_new(yytext+1,strlen(yytext)-2); return STRING; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 583 "slghscan.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 584 "slghscan.l"
{ SleighCompile_nextLine(slgh); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 585 "slghscan.l"
{ return yytext[0]; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 588 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(print,preproc) ); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 589 "slghscan.l"
{ preproc_macroexpand(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 590 "slghscan.l"
{ yylval.ch = yytext[0]; return CH; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 591 "slghscan.l"
{ yylval.ch = '^'; return '^'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 592 "slghscan.l"
{ BEGIN(pattern); actionon=0; return IS_KEY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 593 "slghscan.l"
{  yylval.str = cstr_new(yytext, strlen(yytext)); return SYMBOLSTRING;  }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 594 "slghscan.l"
{ yylval.str = cstr_new(yytext+1,strlen(yytext)-2); return STRING; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 595 "slghscan.l"
{ yylval.ch = ' '; return ' '; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 596 "slghscan.l"
{ SleighCompile_nextLine(slgh); return ' '; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 597 "slghscan.l"
{ return yytext[0]; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 599 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(pattern,preproc) ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 600 "slghscan.l"
{ preproc_macroexpand(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 601 "slghscan.l"
{ BEGIN((withsection==1) ? INITIAL:sem); withsection=0; yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 602 "slghscan.l"
{ BEGIN(INITIAL); return OP_UNIMPL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 603 "slghscan.l"
{ return GLOBALSET_KEY; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 604 "slghscan.l"
{ return OP_RIGHT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 605 "slghscan.l"
{ return OP_LEFT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 606 "slghscan.l"
{ return OP_NOTEQUAL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 607 "slghscan.l"
{ return OP_LESSEQUAL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 608 "slghscan.l"
{ return OP_GREATEQUAL; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 609 "slghscan.l"
{ return OP_AND; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 610 "slghscan.l"
{ return OP_OR; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 611 "slghscan.l"
{ return OP_XOR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 612 "slghscan.l"
{ return ELLIPSIS_KEY; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 613 "slghscan.l"
{ actionon = 1; yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 614 "slghscan.l"
{ actionon = 0; yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 615 "slghscan.l"
{ yylval.ch = yytext[0];  return (actionon==0) ? yytext[0] : OP_AND; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 616 "slghscan.l"
{ yylval.ch = yytext[0];  return (actionon==0) ? yytext[0] : OP_OR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 617 "slghscan.l"
{ return OP_XOR; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 618 "slghscan.l"
{ yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 89:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 619 "slghscan.l"

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 620 "slghscan.l"
{ return find_symbol();   }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 621 "slghscan.l"
{ return scan_number(yytext,&yylval,true); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 622 "slghscan.l"
{ return scan_number(yytext,&yylval,true); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 623 "slghscan.l"
{ return scan_number(yytext,&yylval,true); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 624 "slghscan.l"

	YY_BREAK
case 95:
YY_RULE_SETUP
#line 625 "slghscan.l"
{ SleighCompile_nextLine(slgh); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 626 "slghscan.l"
{ return yytext[0]; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 628 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(sem,preproc) ); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 629 "slghscan.l"
{ preproc_macroexpand(); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 630 "slghscan.l"
{ BEGIN(INITIAL); yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 631 "slghscan.l"
{ return OP_BOOL_OR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 632 "slghscan.l"
{ return OP_BOOL_AND; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 633 "slghscan.l"
{ return OP_BOOL_XOR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 634 "slghscan.l"
{ return OP_RIGHT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 635 "slghscan.l"
{ return OP_LEFT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 636 "slghscan.l"
{ return OP_EQUAL; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 637 "slghscan.l"
{ return OP_NOTEQUAL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 638 "slghscan.l"
{ return OP_LESSEQUAL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 639 "slghscan.l"
{ return OP_GREATEQUAL; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 640 "slghscan.l"
{ return OP_SDIV; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 641 "slghscan.l"
{ return OP_SREM; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 642 "slghscan.l"
{ return OP_SRIGHT; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 643 "slghscan.l"
{ return OP_SLESS; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 644 "slghscan.l"
{ return OP_SGREAT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 645 "slghscan.l"
{ return OP_SLESSEQUAL; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 646 "slghscan.l"
{ return OP_SGREATEQUAL; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 647 "slghscan.l"
{ return OP_FADD; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 648 "slghscan.l"
{ return OP_FSUB; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 649 "slghscan.l"
{ return OP_FMULT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 650 "slghscan.l"
{ return OP_FDIV; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 651 "slghscan.l"
{ return OP_FEQUAL; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 652 "slghscan.l"
{ return OP_FNOTEQUAL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 653 "slghscan.l"
{ return OP_FLESS; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 654 "slghscan.l"
{ return OP_FGREAT; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 655 "slghscan.l"
{ return OP_FLESSEQUAL; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 656 "slghscan.l"
{ return OP_FGREATEQUAL; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 657 "slghscan.l"
{ return OP_ZEXT; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 658 "slghscan.l"
{ return OP_CARRY; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 659 "slghscan.l"
{ return OP_BORROW; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 660 "slghscan.l"
{ return OP_SEXT; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 661 "slghscan.l"
{ return OP_SCARRY; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 662 "slghscan.l"
{ return OP_SBORROW; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 663 "slghscan.l"
{ return OP_NAN; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 664 "slghscan.l"
{ return OP_ABS; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 665 "slghscan.l"
{ return OP_SQRT; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 666 "slghscan.l"
{ return OP_CEIL; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 667 "slghscan.l"
{ return OP_FLOOR; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 668 "slghscan.l"
{ return OP_ROUND; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 669 "slghscan.l"
{ return OP_INT2FLOAT; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 670 "slghscan.l"
{ return OP_FLOAT2FLOAT; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 671 "slghscan.l"
{ return OP_TRUNC; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 672 "slghscan.l"
{ return OP_CPOOLREF; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 673 "slghscan.l"
{ return OP_NEW; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 674 "slghscan.l"
{ return OP_POPCOUNT; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 675 "slghscan.l"
{ return IF_KEY; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 676 "slghscan.l"
{ return GOTO_KEY; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 677 "slghscan.l"
{ return CALL_KEY; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 678 "slghscan.l"
{ return RETURN_KEY; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 679 "slghscan.l"
{ return DELAYSLOT_KEY; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 680 "slghscan.l"
{ return CROSSBUILD_KEY; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 681 "slghscan.l"
{ return EXPORT_KEY; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 682 "slghscan.l"
{ return BUILD_KEY; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 683 "slghscan.l"
{ return LOCAL_KEY; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 684 "slghscan.l"
{ yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 154:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 685 "slghscan.l"

	YY_BREAK
case 155:
YY_RULE_SETUP
#line 686 "slghscan.l"
{ return find_symbol();   }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 687 "slghscan.l"
{ return scan_number(yytext,&yylval,false); }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 688 "slghscan.l"
{ return scan_number(yytext,&yylval,false); }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 689 "slghscan.l"
{ return scan_number(yytext,&yylval,false); }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 690 "slghscan.l"

	YY_BREAK
case 160:
YY_RULE_SETUP
#line 691 "slghscan.l"
{ SleighCompile_nextLine(slgh); }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 692 "slghscan.l"
{ return yytext[0]; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 694 "slghscan.l"
{ SleighCompile_nextLine(slgh); BEGIN( preprocess(preproc,preproc) ); }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 695 "slghscan.l"
{ SleighCompile_nextLine(slgh); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(defblock):
case YY_STATE_EOF(macroblock):
case YY_STATE_EOF(print):
case YY_STATE_EOF(pattern):
case YY_STATE_EOF(sem):
case YY_STATE_EOF(preproc):
#line 697 "slghscan.l"
{ yy_delete_buffer( YY_CURRENT_BUFFER );
          if (!filebuffers.len)
            yyterminate(); 
          yy_switch_to_buffer( fss_back()->lastbuffer );
	  FILE *curfile = fss_back()->file;
	  if (curfile != (FILE *)0)
	    fclose(curfile);
          vm_free(fss_back());
          filebuffers.len--;
          SleighCompile_parseFileFinished(slgh);
        }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 708 "slghscan.l"
ECHO;
	YY_BREAK
#line 2383 "slghscan.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 531 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 531 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 530);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 708 "slghscan.l"
